### ISSUE TITLE
[log_2022-02-04_02-53-09.txt](https://github.com/Nesvilab/FragPipe/files/8000752/log_2022-02-04_02-53-09.txt)

### ISSUE THREAD

**Issue by ihorrible** [Nesvilab/IonQuant#29]
[log_2022-02-04_02-53-09.txt](https://github.com/Nesvilab/FragPipe/files/8000752/log_2022-02-04_02-53-09.txt)

Unfortunately, I have the same error and Change system locale to English (United States) did not help to deal with ???:

java.io.IOException: ???????????? ????? ?? ?????
	at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at java.base/sun.nio.ch.FileDispatcherImpl.write(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.write(Unknown Source)
	at java.base/sun.nio.ch.FileChannelImpl.write(Unknown Source)
	at java.base/java.nio.channels.Channels.writeFullyImpl(Unknown Source)
	at java.base/java.nio.channels.Channels.writeFully(Unknown Source)
	at java.base/java.nio.channels.Channels$1.write(Unknown Source)
	at java.base/java.io.BufferedOutputStream.flushBuffer(Unknown Source)
	at java.base/java.io.BufferedOutputStream.write(Unknown Source)
	at java.base/java.io.DataOutputStream.writeInt(Unknown Source)
	at r.a(Unknown Source)
	at ionquant.IonQuant.<init>(Unknown Source)
	at ionquant.IonQuant.main(Unknown Source)
2022-02-04 02:53:02 [ERROR] - ???????????? ????? ?? ?????
Process 'IonQuant' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 1 remaining tasks

_Originally posted by @ihorrible in https://github.com/Nesvilab/FragPipe/issues/595#issuecomment-1029707210_

**Comment by fcyu** [comment]
Duplicate issue: https://github.com/Nesvilab/FragPipe/issues/595
