### ISSUE TITLE
IonQuant fail to load mzML files 

### ISSUE THREAD

**Issue by assafkacen1** [Nesvilab/IonQuant#44]
Hi,
I am using IonQuant as a stand-alone program. It successfully checks my mzML file but fails to load it with the error: Index 0 out of bounds for length 0. I tried several different mzML, but all failed. I am using msconvert for converting raw files to mzML. The program works well with timsTOF .d data as input. 

log: 
2023-06-18 12:13:01  command : java -Xmx22G -jar /app/bin/IonQuant-1.8.10.jar --threads 7 --ionmobility 1 --minexps 1 --mbr 1 --maxlfq 1 --requantify 1 --mztol 10 --imtol 0.05 --rttol 0.4 --mbrmincorr 0 --mbrrttol 1 --mbrimtol 0.05 --mbrtoprun 10 --ionfdr 0.01 --proteinfdr 1 --peptidefdr 1 --normalization 1 --minisotopes 2 --minscans 3 --writeindex 0 --tp 0 --minfreq 0 --minions 2 --locprob 0.75 --uniqueness 0 --multidir /app/data --filelist /app/data/filelist_ionquant.txt --modlist /app/data/modmasses_ionquant.txt
2023-06-18 12:13:03 IonQuant version IonQuant-1.8.10
2023-06-18 12:13:03 Batmass-IO version 1.28.9
2023-06-18 12:13:03 timsdata library version timsdata-2-21-0-4
2023-06-18 12:13:03 (c) University of Michigan
2023-06-18 12:13:03 System OS: Linux, Architecture: amd64
2023-06-18 12:13:03 Java Info: 17.0.7, OpenJDK 64-Bit Server VM, Debian
2023-06-18 12:13:03 JVM started with 22 GB memory
2023-06-18 12:13:03 2023-06-18 09:13:03 [WARNING] - There are only 2 experiments. Will not calculate MaxLFQ intensity.
2023-06-18 12:13:03 2023-06-18 09:13:03 [INFO] - Collecting variable modifications from all psm.tsv files...
2023-06-18 12:13:04 2023-06-18 09:13:04 [INFO] - Collecting run names from all psm.tsv files...
2023-06-18 12:13:08 2023-06-18 09:13:08 [INFO] - Parameters:
2023-06-18 12:13:08 2023-06-18 09:13:08 [INFO] - threads = 7
2023-06-18 12:13:08 2023-06-18 09:13:08 [INFO] - mztol = 10.0
2023-06-18 12:13:08 2023-06-18 09:13:08 [INFO] - rttol = 0.4
2023-06-18 12:13:08 2023-06-18 09:13:08 [INFO] - imtol = 0.05
2023-06-18 12:13:08 2023-06-18 09:13:08 [INFO] - minisotopes = 2
2023-06-18 12:13:08 2023-06-18 09:13:08 [INFO] - minscans = 3
2023-06-18 12:13:08 2023-06-18 09:13:08 [INFO] - psm = /app/data/HF1_5998_YMER_1013_161017/psm.tsv
2023-06-18 12:13:08 2023-06-18 09:13:08 [INFO] - psm = /app/data/HF1_5998_YMER_1019_161017/psm.tsv
2023-06-18 12:13:08 2023-06-18 09:13:08 [INFO] - multidir = /app/data/
2023-06-18 12:13:08 2023-06-18 09:13:08 [INFO] - excludemods = 
2023-06-18 12:13:08 2023-06-18 09:13:08 [INFO] - minions = 2
2023-06-18 12:13:08 2023-06-18 09:13:08 [INFO] - maxlfq = 0
2023-06-18 12:13:08 2023-06-18 09:13:08 [INFO] - ibaq = 0
2023-06-18 12:13:08 2023-06-18 09:13:08 [INFO] - normalization = 1
2023-06-18 12:13:08 2023-06-18 09:13:08 [INFO] - minexps = 1
2023-06-18 12:13:08 2023-06-18 09:13:08 [INFO] - minfreq = 0.0
2023-06-18 12:13:08 2023-06-18 09:13:08 [INFO] - tp = 0
2023-06-18 12:13:08 2023-06-18 09:13:08 [INFO] - mbr = 1
2023-06-18 12:13:08 2023-06-18 09:13:08 [INFO] - mbrrttol = 1.0
2023-06-18 12:13:08 2023-06-18 09:13:08 [INFO] - mbrimtol = 0.05
2023-06-18 12:13:08 2023-06-18 09:13:08 [INFO] - mbrtoprun = 10
2023-06-18 12:13:08 2023-06-18 09:13:08 [INFO] - mbrmincorr = 0.0
2023-06-18 12:13:08 2023-06-18 09:13:08 [INFO] - ionmobility = 1
2023-06-18 12:13:08 2023-06-18 09:13:08 [INFO] - ionfdr = 0.01
2023-06-18 12:13:08 2023-06-18 09:13:08 [INFO] - peptidefdr = 1.0
2023-06-18 12:13:08 2023-06-18 09:13:08 [INFO] - proteinfdr = 1.0
2023-06-18 12:13:08 2023-06-18 09:13:08 [INFO] - light = 
2023-06-18 12:13:08 2023-06-18 09:13:08 [INFO] - medium = 
2023-06-18 12:13:08 2023-06-18 09:13:08 [INFO] - heavy = 
2023-06-18 12:13:08 2023-06-18 09:13:08 [INFO] - requantify = 0
2023-06-18 12:13:08 2023-06-18 09:13:08 [INFO] - writeindex = 0
2023-06-18 12:13:08 2023-06-18 09:13:08 [INFO] - locprob = 0.75
2023-06-18 12:13:08 2023-06-18 09:13:08 [INFO] - uniqueness = 0
2023-06-18 12:13:08 2023-06-18 09:13:08 [INFO] - filelist = /app/data/filelist_ionquant.txt
2023-06-18 12:13:08 2023-06-18 09:13:08 [INFO] - specdir = /app/data
2023-06-18 12:13:08 2023-06-18 09:13:08 [INFO] - modlist = /app/data/modmasses_ionquant.txt
2023-06-18 12:13:08 2023-06-18 09:13:08 [INFO] - mod masses:
2023-06-18 12:13:08 2023-06-18 09:13:08 [INFO] - 15.9949
2023-06-18 12:13:08 2023-06-18 09:13:08 [INFO] - 42.0106
2023-06-18 12:13:08 2023-06-18 09:13:08 [INFO] - 57.0214
2023-06-18 12:13:08 2023-06-18 09:13:08 [INFO] - 79.96633
2023-06-18 12:13:08 2023-06-18 09:13:08 [INFO] - Checking /app/data/HF1_5998_YMER_1013_161017.mzML...
2023-06-18 12:13:18 2023-06-18 09:13:18 [INFO] - Checking /app/data/HF1_5998_YMER_1019_161017.mzML...
2023-06-18 12:13:25 2023-06-18 09:13:25 [INFO] - Loading /app/data/HF1_5998_YMER_1013_161017.mzML...
2023-06-18 12:13:37 java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
2023-06-18 12:13:37     at ionquant.IonQuant.<init>(Unknown Source)
2023-06-18 12:13:37     at ionquant.IonQuant.main(Unknown Source)
2023-06-18 12:13:37 2023-06-18 09:13:37 [ERROR] - Index 0 out of bounds for length 0

**Comment by fcyu** [comment]
Have you tried FragPipe with the latest versions of FragPipe, MSFragger, Philosopher, and IonQuant? If you still see the same error, could you share the log file?

Thanks,

Fengchao

**Comment by assafkacen1** [comment]
FragPipe works well, but my pipeline is built from separate steps. I can't figure out why for .d files, it works fine, and those mzML files are being processed successfully by MSFragger in previous steps.  The only error I get is when IonQuant is activated on those files.

**Comment by fcyu** [comment]
If IonQuant works well in FragPipe, but not standalone, there must be issues in your commands or parameters. Pleas double check them including the filelist_ionquant.txt file.

Best,

Fengchao
