### ISSUE TITLE
stat lib: No such file or directory when running ionquant on linux

### ISSUE THREAD

**Issue by wuwo007** [Nesvilab/IonQuant#57]
Hello，
I am using Fragpipe (LFQ_MBR.workflow) on a Linux server to process a batch of DDA TimsTOF data. The MSFragger log shows an error occurring during the last step, ionquant. So, I found the command for ionquant in the log file and reran it on the command line. However, the error appears again. The main error is :
2024-09-14 16:04:28 [INFO] - Loading /ailab/group/pjlab-ai4s/aim/gaozhiqiang/ms_data/msdata_zeng/AD8-200DDA/raws/timsTOF_lwy_H15-500nl_Plasma_AD_200_DDA_A-80_Slot1-34_1_2542.d...
2024-09-14 16:04:29 [INFO] - ...20%...stat lib: No such file or directory
addr2line: Reading source function failed for module /ailab/user/gaozhiqiang/.cache/JNA/temp/jna2643107734330031219.tmp
stat lib: No such file or directory
addr2line: Writing address value failed for module /ailab/user/gaozhiqiang/.cache/JNA/temp/jna2643107734330031219.tmp
stat lib: No such file or directory
addr2line: Writing address value failed for module /ailab/user/gaozhiqiang/.cache/JNA/temp/jna2643107734330031219.tmp
stat lib: No such file or directory
addr2line: Writing address value failed for module /ailab/user/gaozhiqiang/.cache/JNA/temp/jna2643107734330031219.tmp
stat lib: No such file or directory
addr2line: Writing address value failed for module /ailab/user/gaozhiqiang/.cache/JNA/temp/jna2643107734330031219.tmp
dladdr failed to resolve the address for module <unknown>
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Timsdata could not open the file
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at i.<init>(Unknown Source)
        at ionquant.IonQuant.<init>(Unknown Source)
        at ionquant.IonQuant.a(Unknown Source)
        at ionquant.IonQuant.main(Unknown Source)
Caused by: java.lang.IllegalStateException: Timsdata could not open the file
        at umich.ms.fileio.filetypes.bruker.BrukerTdfFile.setupJna(BrukerTdfFile.java:104)
        at umich.ms.fileio.filetypes.bruker.BrukerTdfFile.<init>(BrukerTdfFile.java:75)
        at umich.ms.fileio.filetypes.bruker.BrukerTdfFileBase.<init>(BrukerTdfFileBase.java:70)
        at i.a(Unknown Source)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
        at i.a(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
2024-09-14 16:04:32 [ERROR] - java.lang.IllegalStateException: Timsdata could not open the file

The more log is attached.
What could be the reason for this? Any suggestions for resolving it?

[ionquant_log.txt](https://github.com/user-attachments/files/17001787/ionquant_log.txt)

**Comment by wuwo007** [comment]
The command statement I ran is as follow:
java -Djava.awt.headless=true -Xmx50G -Dlibs.bruker.dir=/ailab/group/groups/aim/gaozhiqiang/code/dia_denovo/fragpipe_v22/fragpipe/tools/MSFragger-4.1/ext/bruker -Dlibs.thermo.dir=/ailab/group/groups/aim/gaozhiqiang/code/dia_denovo/fragpipe_v22/fragpipe/tools/MSFragger-4.1/ext/thermo -cp /ssd/home/groups/aim/gaozhiqiang/code/dia_denovo/fragpipe_v22/fragpipe/tools/jfreechart-1.5.3.jar:/ssd/home/groups/aim/gaozhiqiang/code/dia_denovo/fragpipe_v22/fragpipe/tools/batmass-io-1.33.4.jar:/ailab/group/groups/aim/gaozhiqiang/code/dia_denovo/fragpipe_v22/fragpipe/tools/IonQuant-1.10.27.jar ionquant.IonQuant --threads 20 --perform-ms1quant 1 --perform-isoquant 0 --isotol 20.0 --isolevel 2 --isotype tmt10 --ionmobility 1 --site-reports 1 --msstats 1 --minexps 1 --mbr 1 --maxlfq 1 --requantify 1 --mztol 10 --imtol 0.05 --rttol 0.4 --mbrmincorr 0 --mbrrttol 1 --mbrimtol 0.05 --mbrtoprun 10 --ionfdr 0.01 --proteinfdr 1 --peptidefdr 1 --normalization 1 --minisotopes 2 --minscans 3 --writeindex 0 --tp 0 --minfreq 0 --minions 1 --locprob 0.75 --uniqueness 0 --multidir . --filelist /ailab/group/pjlab-ai4s/aim/gaozhiqiang/ms_data/msdata_zeng/AD8-200DDA/all_sap_ref_search_result/filelist_ionquant.txt --modlist /ailab/group/pjlab-ai4s/aim/gaozhiqiang/ms_data/msdata_zeng/AD8-200DDA/all_sap_ref_search_result/modmasses_ionquant.txt

**Comment by fcyu** [comment]
I guess `/ailab/group/pjlab-ai4s/aim/gaozhiqiang/ms_data/msdata_zeng/AD8-200DDA/raws/timsTOF_lwy_H15-500nl_Plasma_AD_200_DDA_A-80_Slot1-34_1_2542.d` was corrupted.

Best,

Fengchao

**Comment by wuwo007** [comment]
Thanks， I downloaded the timsTOF_lwy_H15-500nl_Plasma_AD_200_DDA_A-80_Slot1-34_1_2542.d again, it works.

**Comment by fcyu** [comment]
Thank you for the feedback.

Best,

Fengchao
